version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
    commit-message:
      prefix: "chore(deps)"
    groups:
          all-dependencies:
            patterns:
              - "*"
