name: Update Song Data

on:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: npm ci

      - name: Fetch latest master data
        run: npm run update-master

      - name: Upload song data artifact
        uses: actions/upload-artifact@v4
        with:
          name: songs-data
          path: public/data/songs.json
          retention-days: 90
