name: Update Master Data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install dependencies
        run: npm ci

      - name: Fetch latest master data
        run: npm run update-master

      - name: Data Preparation
        run: |
          mkdir -p ./staging/data
          cp ./public/data/songs.json ./staging/data/

      - name: Deploy data file to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./staging
          keep_files: true
          commit_message: "chore: Update songs.json by manual"
